; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

; reserve space for a LittleFS partition (pick size that fits your flash)
board_build.filesystem = littlefs
board_build.filesystem_size = 1m

; debug_tool = cmsis-dap
; debug_speed = 35000
; upload_protocol = cmsis-dap
; upload_protocol = picoprobe
build_type = debug

lib_deps = 
  https://github.com/vicharak-in/shrike_arduino.git
